# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-26 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigapp', '0003_feedbackdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Mobile', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('courses', models.CharField(max_length=100)),
            ],
        ),
    ]
