# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-27 06:28
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bigapp', '0004_enquirydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirydata',
            name='courses',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PY', 'Python'), ('DJ', 'Django'), ('RA', 'Rest-Api'), ('FL', 'Flask'), ('UI', 'Ui')], max_length=14),
        ),
    ]
